### PR TITLE
Small tweaks to allow Julia 1.5.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by staticfloat** [comment]
I'm only 40% convinced that we should even allow people to use this on 1.5.  I don't think it should be legal to run this without the ability to GC.

**Comment by fredrikekre** [comment]
You can still gc by using 1.6 though?

**Comment by staticfloat** [comment]
True, although there's still the possibility that some users will stay on 1.5 for a while.

I suppose it gives us an on-ramp to get people upgraded to 1.6.  :) "Move to 1.6 and it'll actually _save_ you disk space!".  ;)

**Comment by fredrikekre** [comment]
I was mostly annoyed that I always accidentally started 1.5 when testing :) And also that it might be nice with some beta-testing. We could also implement some basic GC as `Scratch.gc()` I guess.

**Pull request merged**
